spring.application.name=e-commerce

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=info
logging.level.org.hibernate.SQL=debug

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/openapi.yaml
